# Generated by Django 5.1 on 2024-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_Thumbnail',
            field=models.ImageField(blank=True, default='blogThumbnail/default_image.jpg', null=True, upload_to=''),
        ),
    ]
