# Generated by Django 5.1 on 2024-08-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_Thumbnail',
            field=models.ImageField(blank=True, default='blogThumbnils/default_image.jpg', null=True, upload_to='blogThumbnils/'),
        ),
    ]
